version: "3"
services:
  nginx:
    image: admins-MBP:5000/docker-nginx-simple:latest
    #image: nginx-simple:latest
    container_name: nginx-simple
    restart: always
    ports:
      - 80:80
    #network_mode: "bridge"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
    networks:
      - nginx-network
networks:
  nginx-network:
    ##a custom driver
    #driver: custom-driver-1
    #https://docs.docker.com/compose/networking/#specify-custom-networks
