apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: admins-MBP:5000/docker-nginx-simple:latest
        imagePullPolicy: IfNotPresent
        name: nginx-simple
        ports:
        - containerPort: 80
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/www/
          name: nginx-claim0
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
status: {}
