apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-claim0
  name: nginx-claim0
spec:
  storageClassName: nginx-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      io.kompose.service: nginx-claim0
      #release: "stable"
  #selector:
    #io.kompose.service: nginx-claim0
status: {}
