apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv001
  labels:
    io.kompose.service: nginx-claim0
spec:
  capacity:
    storage: 100Mi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nginx-nfs
  #storageClassName: standard
  #storageClassName: slow
  mountOptions:
    - nfsvers=2
    - udp
    #- hard
    #- intr
    #- tcp
    #- nfsvers=4.1
  nfs:
    #path: /tmp/k8s-nfs
    #path: /Users
    path: /Users/home/dev/myappsnsites/docker-nginx-simple/wwwroot
    #path: /tmp/docker-nginx-simple/wwwroot
    server: 192.168.99.1
    #server: 127.0.0.1
    #server: 172.17.0.2
